'use client';

import React from 'react';
import Link from 'next/link';
import { 
  BookOpen, 
  Zap, 
  ShieldCheck, 
  Sparkles, 
  ArrowRight, 
  Github,
  LayoutDashboard
} from 'lucide-react';

export default function HomePage() {
  return (
    <div className="min-h-screen bg-white text-slate-900 font-sans selection:bg-blue-100 selection:text-blue-900">
      
      {/* 1. Navigation Bar */}
      <nav className="fixed top-0 w-full z-50 bg-white/80 backdrop-blur-md border-b border-slate-100">
        <div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="bg-blue-600 p-2 rounded-xl shadow-lg shadow-blue-200">
              <BookOpen className="text-white" size={24} />
            </div>
            <span className="text-xl font-black tracking-tighter uppercase">QuizAI</span>
          </div>

          <div className="hidden md:flex items-center space-x-8 text-sm font-bold text-slate-500">
            <a href="#features" className="hover:text-blue-600 transition">Features</a>
            <a href="#how-it-works" className="hover:text-blue-600 transition">How it Works</a>
            <Link href="/login" className="text-slate-900 hover:text-blue-600 transition">Sign In</Link>
            <Link 
              href="/login" 
              className="bg-slate-900 text-white px-6 py-2.5 rounded-full hover:bg-blue-600 transition shadow-lg shadow-slate-200"
            >
              Get Started
            </Link>
          </div>
        </div>
      </nav>

      {/* 2. Hero Section */}
      <section className="pt-40 pb-20 px-6 relative overflow-hidden">
        {/* Decorative Background Glows */}
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full h-full -z-10">
          <div className="absolute top-20 left-1/4 w-72 h-72 bg-blue-400/20 rounded-full blur-[120px] animate-pulse" />
          <div className="absolute top-40 right-1/4 w-96 h-96 bg-purple-400/10 rounded-full blur-[120px]" />
        </div>

        <div className="max-w-5xl mx-auto text-center">
          <div className="inline-flex items-center space-x-2 bg-blue-50 text-blue-700 px-4 py-2 rounded-full mb-8 border border-blue-100 animate-bounce">
            <Sparkles size={16} />
            <span className="text-xs font-black uppercase tracking-widest">AI-Powered Learning</span>
          </div>
          
          <h1 className="text-6xl md:text-8xl font-black tracking-tighter leading-[0.9] mb-8">
            Turn your notes into <span className="text-blue-600">mastery.</span>
          </h1>
          
          <p className="text-xl md:text-2xl text-slate-500 font-medium max-w-2xl mx-auto mb-10 leading-relaxed">
            Upload your study materials and let our AI generate personalized quizzes, summaries, and practice sessions in seconds.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Link 
              href="/login" 
              className="w-full sm:w-auto px-10 py-5 bg-slate-900 text-white rounded-[24px] font-black text-lg hover:bg-blue-600 transition-all flex items-center justify-center space-x-3 shadow-2xl hover:-translate-y-1"
            >
              <span>Start Learning Free</span>
              <ArrowRight size={22} />
            </Link>
            <Link 
              href="/library" 
              className="w-full sm:w-auto px-10 py-5 bg-white text-slate-900 border-2 border-slate-100 rounded-[24px] font-black text-lg hover:bg-slate-50 transition-all flex items-center justify-center space-x-3 shadow-sm"
            >
              <LayoutDashboard size={22} />
              <span>Go to Library</span>
            </Link>
          </div>
        </div>
      </section>

      {/* 3. Features Section */}
      <section id="features" className="py-24 px-6 bg-slate-50">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-20">
            <h2 className="text-4xl font-black tracking-tight mb-4">Study smarter, not harder.</h2>
            <p className="text-slate-500 font-medium">Everything you need to crush your next exam.</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            {/* Feature 1 */}
            <div className="bg-white p-10 rounded-[40px] border border-slate-100 shadow-sm hover:shadow-xl transition-all group">
              <div className="w-14 h-14 bg-blue-50 text-blue-600 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                <Zap size={28} />
              </div>
              <h3 className="text-2xl font-black mb-4">Instant Quizzes</h3>
              <p className="text-slate-500 leading-relaxed font-medium">
                Paste your notes and get a full CBT-style quiz generated by Llama 3.3 in seconds.
              </p>
            </div>

            {/* Feature 2 */}
            <div className="bg-white p-10 rounded-[40px] border border-slate-100 shadow-sm hover:shadow-xl transition-all group">
              <div className="w-14 h-14 bg-purple-50 text-purple-600 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-purple-600 group-hover:text-white transition-colors">
                <ShieldCheck size={28} />
              </div>
              <h3 className="text-2xl font-black mb-4">Private Vault</h3>
              <p className="text-slate-500 leading-relaxed font-medium">
                Your study sessions are private. Only you can access your history and quiz results.
              </p>
            </div>

            {/* Feature 3 */}
            <div className="bg-white p-10 rounded-[40px] border border-slate-100 shadow-sm hover:shadow-xl transition-all group">
              <div className="w-14 h-14 bg-green-50 text-green-600 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-green-600 group-hover:text-white transition-colors">
                <Sparkles size={28} />
              </div>
              <h3 className="text-2xl font-black mb-4">AI Summaries</h3>
              <p className="text-slate-500 leading-relaxed font-medium">
                Long lectures? We distill thousands of words into actionable, easy-to-read summaries.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 4. Footer */}
      <footer className="py-12 border-t border-slate-100 text-center">
        <div className="flex justify-center space-x-6 mb-6 text-slate-400">
           <Github size={24} className="hover:text-slate-900 cursor-pointer" />
        </div>
        <p className="text-slate-400 font-bold text-sm tracking-widest uppercase">
          &copy; 2026 QuizAI. Built for students.
        </p>
      </footer>

    </div>
  );
}